[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vector_tile_base"
version = "1.0.2"
description = "Python implementation of Mapbox vector tiles"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
    {name = "Sean Gillies", email = "sean@mapbox.com"}
]
requires-python = ">=3.9"
dependencies = [
    "protobuf>=3.20.0",
]

[tool.setuptools]
packages = ["vector_tile_base"] 